### PR TITLE
Solved issue: Create Auth screen

### PR DESCRIPTION
**Pull request by CeeTeeDee**
So @irvanalfaridzi , I have successfully add both login and sign up screen to project. Hope you can check my progress soon, I also took the liberty of adding some dependencies in pubspec.yaml.

### CODE REVIEW

**Comment by GreenHornOx** [comment]
Login
Sign up

**Comment by CeeTeeDee** [comment]
Login
Sign up

**Comment by irvanalfaridzi** [comment]
Hai @CeeTeeDee thanks for the PR
If I'm not wrong, the image above is the result of your work, right? the UI result is good, appreciate it 🙌🏻 
But I think you wrongly understand what actually the issue is and the expected result for the issue. 

The UI result of login and create new account screen should be like the image attached in issue no 2. Should be like the image below. You can get the UI design Figma on the [README.md](https://github.com/stikom-valley/food-app#getting-started) in Section Getting Started no 3 and start slicing the design to the Flutter. Please kindly read the documentation for a deeper understanding of the project 🙌🏻

image

**Comment by CeeTeeDee** [comment]
@irvanalfaridzi Sorry, but I got all these line up just a few weeks ago so this is the best that I can do. Also please keep in mind that you shouldn't merge all of them, only the new codes will do. Some of the code have been deprecated so I tweak a little in the build.gradle files and it didn't turn out well.

**Comment by irvanalfaridzi** [comment]
@CeeTeeDee no problem. I can't approve and merge your PR since it is not the expected result. I have checked it and yes, there is an issue with the version of compileSdkVersion, minSdkVersion, and multidexing. You can simply change the `compileSdkVersion 32`, `minSdkVersion 20,` and add `multiDexEnabled true` to the defaultConfig on the build.gradle

Do you want to continue to resolve this issue by slicing the correct UI design? If not, it's okay. If you don't mind, I will close this PR

**Comment by CeeTeeDee** [comment]
Closing the PR

> @CeeTeeDee no problem. I can't approve and merge your PR since it is not the expected result. I have checked it and yes, there is an issue with the version of compileSdkVersion, minSdkVersion, and multidexing. You can simply change the `compileSdkVersion 32`, `minSdkVersion 20,` and add `multiDexEnabled true` to the defaultConfig on the build.gradle
> 
> Do you want to continue to resolve this issue by slicing the correct UI design? If not, it's okay. If you don't mind, I will close this PR

You can close the PR

**Pull request closed without merging**
